# Generated by Django 3.2.9 on 2023-06-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
