# Generated by Django 3.2.9 on 2023-05-30 11:30

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ecommerce.apps.products.models.upload_image_digital_path, verbose_name='fichier')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='article')),
            ],
            options={
                'verbose_name': 'Fichier Article Digital',
                'verbose_name_plural': 'Fichiers Articles Digitaux',
            },
        ),
    ]
