# Generated by Django 3.2.9 on 2023-05-30 12:23

import django.core.files.storage
from django.db import migrations, models
import ecommerce.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_digitalproductfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproductfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/abdulkabirkeita/Sites/service/core/core/static_cdn/protected_media'), upload_to=ecommerce.apps.products.models.upload_product_file_loc, verbose_name='fichier'),
        ),
    ]
