# Generated by Django 3.2.9 on 2023-06-01 09:32

from django.db import migrations, models
import ecommerce.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='article')),
                ('image', models.ImageField(upload_to=ecommerce.apps.products.models.upload_image_path, verbose_name='Image')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
    ]
