# Generated by Django 3.2.9 on 2023-06-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_base'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base',
            new_name='Hero',
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Hero'},
        ),
    ]
