# Generated by Django 3.2.9 on 2023-06-01 11:57

from django.db import migrations, models
import ecommerce.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230601_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='titre')),
                ('image', models.ImageField(upload_to=ecommerce.apps.products.models.upload_image_path)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
