# Generated by Django 3.2.9 on 2023-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_herosection_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ('-id',), 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AddField(
            model_name='product',
            name='item_promo',
            field=models.BooleanField(default=False, verbose_name='en promo'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='name',
            field=models.CharField(blank=True, default='hero', max_length=150, null=True, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='articles phares'),
        ),
    ]
