# Generated by Django 3.2.9 on 2023-06-09 12:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, max_length=300, null=True, verbose_name='Twitter')),
                ('whatsapp', models.URLField(blank=True, max_length=300, null=True, verbose_name='WhatsApp')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+224611111183', max_length=128, region=None, verbose_name='Téléphone')),
                ('email', models.EmailField(default='contact@itservices.com', max_length=254)),
                ('address', models.TextField(default='Taouya Petit carrefour petit lac commune de Ratoma, Conakry République de Guinée', verbose_name='adresse')),
                ('website', models.URLField(default='www.itservicesgn.com', verbose_name='site web')),
                ('post_box', models.IntegerField(default='403', verbose_name='boite postale')),
            ],
            options={
                'verbose_name': 'Reseau social',
                'verbose_name_plural': 'Reseaux sociaux',
            },
        ),
    ]
