# Generated by Django 3.2.9 on 2023-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='post_box',
            field=models.IntegerField(default='403', verbose_name='boite postale'),
        ),
        migrations.AddField(
            model_name='social',
            name='website',
            field=models.URLField(default='www.itservicesgn.com', verbose_name='site web'),
        ),
    ]
