# Generated by Django 3.2.9 on 2023-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20230603_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='website',
            field=models.URLField(default='https://www.itservicesgn.com/', verbose_name='site web'),
        ),
    ]
