# Generated by Django 3.2.9 on 2023-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_social_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='address',
            field=models.TextField(default='Taouya Petit carrefour petit lac commune de Ratoma, Conakry République de Guinée', verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='social',
            name='email',
            field=models.EmailField(default='contact@itservices.com', max_length=254),
        ),
    ]
