# Generated by Django 3.2.9 on 2023-06-03 15:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20230603_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+224611111183', max_length=128, region=None, verbose_name='Téléphone'),
        ),
    ]
