# Generated by Django 3.2.9 on 2023-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_social_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='website',
            field=models.URLField(default='www.itservicesgn.com', verbose_name='site web'),
        ),
    ]
