# Generated by Django 3.2.9 on 2023-06-03 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('products', '0001_initial'),
        ('billing', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=120, verbose_name='N commande')),
                ('refunded', models.BooleanField(default=False, verbose_name='article retourné ?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile', verbose_name='adresse de livraison')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Produit acheté',
                'verbose_name_plural': 'Produits achetés',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=150, verbose_name='N° commande')),
                ('status', models.CharField(choices=[('created', 'commande créée'), ('paid', 'paiement effectué'), ('shipped', 'commande livrée'), ('refunded', 'commande remboursée')], default='created', max_length=150)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=9.99, max_digits=100, verbose_name='frais de livraison')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='total')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de creation')),
                ('active', models.BooleanField(default=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile', verbose_name='client')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='addresses.adresse', verbose_name='adresse de facturation')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='panier')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.adresse', verbose_name='adresse de livraison')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ('-id',),
            },
        ),
    ]
