# Generated by Django 3.2.9 on 2023-06-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shipping_total',
        ),
    ]
