# Generated by Django 3.2.9 on 2023-06-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orders_shipping_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière modification'),
        ),
    ]
