# Generated by Django 3.2.9 on 2023-06-04 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dernière modification'),
        ),
    ]
