# Generated by Django 3.2.9 on 2023-06-03 14:58

from django.db import migrations, models
import ecommerce.apps.about.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to=ecommerce.apps.about.models.upload_about_path)),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='titre')),
                ('introduction', tinymce.models.HTMLField(default='')),
                ('question', models.CharField(max_length=150)),
                ('answer', tinymce.models.HTMLField(help_text='reponse à la question frequement posée')),
            ],
            options={
                'verbose_name': 'Foire aux questions',
                'verbose_name_plural': 'Foires aux questions',
            },
        ),
    ]
