# Generated by Django 3.2.9 on 2023-06-09 12:39

from django.db import migrations, models
import ecommerce.apps.about.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='titre')),
                ('introduction', tinymce.models.HTMLField(default='')),
                ('question', models.CharField(max_length=150)),
                ('answer', tinymce.models.HTMLField(help_text='reponse à la question frequement posée')),
            ],
            options={
                'verbose_name': 'Foire aux questions',
                'verbose_name_plural': 'Foires aux questions',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='intervention')),
            ],
            options={
                'verbose_name': "Domaine d'Intervention",
                'verbose_name_plural': "Domaines d'Interventions",
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ref', max_length=150, unique=True, verbose_name='partenaire')),
                ('image', models.ImageField(upload_to=ecommerce.apps.about.models.upload_about_path)),
            ],
            options={
                'verbose_name': 'Nos partenaire',
                'verbose_name_plural': 'Nos partenaires',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', tinymce.models.HTMLField(default="À PROPOS D'IT SERVICES")),
                ('overview', tinymce.models.HTMLField(default='IT SERVICE SARL est un intégrateur système spécialisé dans le domaine réseaux et sécurité informatique. Immatricule au registre du commerce et du crédit immobilier sous la référence GC.KAL.2017.B.080 022', help_text='brève description du service')),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('intervention', models.ManyToManyField(blank=True, to='about.Intervention')),
                ('reference', models.ManyToManyField(blank=True, to='about.Reference')),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
    ]
