# Generated by Django 3.2.9 on 2023-06-03 15:51

from django.db import migrations, models
import ecommerce.apps.about.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='partenaire')),
                ('image', models.ImageField(upload_to=ecommerce.apps.about.models.upload_about_path)),
            ],
            options={
                'verbose_name': 'Nos partenaire',
                'verbose_name_plural': 'Nos partenaires',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='overview',
            field=tinymce.models.HTMLField(default='IT SERVICE SARL est un intégrateur système spécialisé dans le domaine réseaux et sécurité informatique. Immatricule au registre du commerce et du crédit immobilier sous la référence GC.KAL.2017.B.080 022', help_text="description d'IT SERVICES", verbose_name=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=tinymce.models.HTMLField(default='A PROPOS DE IT SERVICES'),
        ),
        migrations.AddField(
            model_name='about',
            name='reference',
            field=models.ManyToManyField(blank=True, null=True, to='about.Reference'),
        ),
    ]
