# Generated by Django 3.2.9 on 2023-06-03 15:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20230603_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='reference',
            field=models.ManyToManyField(blank=True, to='about.Reference'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=tinymce.models.HTMLField(default="A PROPOS D'IT SERVICES"),
        ),
    ]
