# Generated by Django 3.2.9 on 2023-06-03 15:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20230603_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=tinymce.models.HTMLField(default="À PROPOS D'IT SERVICES"),
        ),
    ]
