# Generated by Django 3.2.9 on 2023-06-03 16:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='intervention')),
            ],
            options={
                'verbose_name': "Domaine d'Intervention",
                'verbose_name_plural': "Domaines d'Interventions",
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='overview',
            field=tinymce.models.HTMLField(default='IT SERVICE SARL est un intégrateur système spécialisé dans le domaine réseaux et sécurité informatique. Immatricule au registre du commerce et du crédit immobilier sous la référence GC.KAL.2017.B.080 022', help_text='brève description du service'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(default='ref', max_length=150, unique=True, verbose_name='partenaire'),
        ),
        migrations.AddField(
            model_name='about',
            name='intervention',
            field=models.ManyToManyField(blank=True, to='about.Intervention'),
        ),
    ]
