# Generated by Django 3.2.9 on 2023-06-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'ordering': ('-id',), 'verbose_name': "Adresse d'expédition", 'verbose_name_plural': "Adresses d'expédition"},
        ),
    ]
